// Code generated by go generate
// This file was generated by robots at 2021-07-29 21:48:34.305977 +0000 UTC
package enum

// Flags is an optional Flags
type Flags int

const (
	Ldate Flags = 1 << iota
	Ltime
	Lmicroseconds
	Llongfile
	Lshortfile
	LUTC
	LstdFlags
)

var flags = [...]string{
	"Ldate", "Ltime", "Lmicroseconds", "Llongfile", "Lshortfile", "LUTC", "LstdFlags",
}

func (f Flags) String() string {
	return flags[f-1]
}

/*
Types pulls full list as []string
*/
func (f Flags) Types() []string {
	return flags[:]
}
