// Code generated by go generate
// This file was generated by robots at 2018-05-21 16:26:06.261281984 +0000 UTC
package enum

// LogLevel is an optional LogLevel
type LogLevel int

const (
	NONE LogLevel = 1 + iota
	FATAL
	FATALNOEXIT
	ERROR
	WARN
	INFO
	DEBUG
	DBGL2
	DBGL3
)

var loglevel = [...]string{
	"NONE", "FATAL", "FATALNOEXIT", "ERROR", "WARN", "INFO", "DEBUG", "DBGL2", "DBGL3",
}

func (l LogLevel) String() string {
	return loglevel[l-1]
}

/*
Types pulls full list as []string
*/
func (l LogLevel) Types() []string {
	return loglevel[:]
}
